### ISSUE TITLE
what's the purpose of std folder inside scapix ?

### ISSUE THREAD

**Issue by supreme-core** [scapix-com/scapix#1]
Excuse me, sir.

I would like to understand how to adjust the compiler options for scapix. Can I force scapix to use a particular version of gcc or g++ or clang or llvm ? 

I also notice there is a folder at https://github.com/scapix-com/scapix/tree/master/std that contains sources for clang and libcxx, how to do I find out if those files are compatible with the compiler I am using. 

Using scapix yields errors related to 'std' folder and stdlib.h

/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/stdlib.h:38:12: error: 
      no member named 'abort' in namespace 'std'
using std::abort;
      ~~~~~^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/stdlib.h:39:12: error: 
      no member named 'atexit' in namespace 'std'
using std::atexit;
      ~~~~~^
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/stdlib.h:40:12: error: 
      no member named 'exit' in namespace 'std'
using std::exit;
      ~~~~~^

scapix/std/libcxxstdlib.h:111:82: error: 
      use of undeclared identifier 'labs'; did you mean 'abs'?
  ...long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
/scapix/std/libcxx/stdlib.h:113:81: error: 
      use of undeclared identifier 'llabs'
  ...long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                                    ^
/scapix/std/libcxx/stdlib.h:116:35: error: 
      unknown type name 'ldiv_t'
inline _LIBCPP_INLINE_VISIBILITY  ldiv_t div(     long __x,      long __y) ...

/scapix/std/libcxx/stdlib.h:116:95: error: 
      use of undeclared identifier 'ldiv'; did you mean 'div'?
  ...ldiv_t div(     long __x,      long __y) _NOEXCEPT {return  ldiv(__x, __y);}

/scapix/std/libcxx/cstdlib:101:9: error: 
      no member named 'div_t' in the global namespace
using ::div_t;

**Comment by supreme-core** [comment]
From the cmake log, I notice it defaults to /usr/lib/gcc/x86_64-linux-gnu/8
Does scapix work with all the compilers ?
I try to change it using
sudo update-alternatives --config gcc
sudo update-alternatives --config g++

but it always to default to 8, I guess I can just uninstall gcc/g++ 8.

-- Generating done
-- Build files have been written to: /home/eric/Downloads/rsocket_playground/rsocket-cpp-scapix_v3Ptr/rsocket-cpp/_build/python
[  3%] Built target yarpl
[  4%] Built target scapix
[  5%] Running Scapix Bridge for rsocket/transports/tcp/TcpDuplexConnection.h
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: 
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Candidate multilib: .;@m64
Selected multilib: .;@m64
clang version 8.0.0 (tags/RELEASE_800/final)

**Comment by Boris-Rasin** [comment]
There are two different "compilers" involved here. First is your system C++ compiler/stdlib, which is used to compile your project, including C++ source and header files generated by Scapix. This can be any C++17 compiler: clang, gcc, msvc, etc. The second "compiler" is Scapix itself: Scapix executable internally utilizes Clang compiler (currently version 8.0.0) in order to parse C++ headers and generate bindings to other languages. The 'std' folder inside Scapix contains stdlib files for this internal "compiler".

**Comment by supreme-core** [comment]
Thank you sir!
