### ISSUE TITLE
Q: Support for POD structs

### ISSUE THREAD

**Issue by eserg** [scapix-com/scapix#11]
Hello,

If I understand the documentation correctly, and am not making mistakes in my tests, plain `struct` export is not supported by Scapix.

**Could you please elaborate technical reasons to this decision?**

Example:
```
struct MyData { 
  int a; 
  double b; 
};
```

```
class MyExportedClass : public scapix::bridge::object<MyExportedClass> {
public:
  MyData someData() const;
};
```
will result in a missing wrapper: `//-(!UNKNOWN!)someData;`

Thank you!

Best regards,
 Sergey

**Comment by Boris-Rasin** [comment]
I plan to add support for POD structs. The technical difficulty is related to separate compilation - deciding where to generate code for such structs. At least structs declared in the same header with one of scapix::bridge::object should not be a problem. I will add such support soon.

**Comment by eserg** [comment]
Thank you, Boris.

> structs declared in the same header with one of `scapix::bridge::object` should not be a problem

Even this support would be a very useful addition.

**Comment by Boris-Rasin** [comment]
Struct support was added 2021-05-10 (cmodule v1.0.29).

This includes structs with members of all supported types, not only POD structs. At this time, only struct defined in the same header where it is used as a parameter or return value is supported. This limitation will be lifted in a future version.
