### ISSUE TITLE
Undefined symbols on macOS 10.13.6

### ISSUE THREAD

**Issue by osdeverr** [scapix-com/scapix#14]
Your scapix-bin has been built on 10.15 and is incompatible with older versions: I'd suggest recompiling it using an older target.
![image](https://user-images.githubusercontent.com/10074604/87308269-a6221480-c523-11ea-9c89-cf7064a94ed6.png)

**Comment by Boris-Rasin** [comment]
Thanks, I will rebuild for an older OS version.
Do you think 10.13 is good enough, or should I target an even older OS version?

**Comment by fanckush** [comment]
I would suggest at least 10.12 if possible

**Comment by osdeverr** [comment]
_Apparently GitHub didn't send my comment. Writing it again._

@Boris-Rasin thanks for your reply! 10.12 would probably be better as @fanckush said.

**Comment by Boris-Rasin** [comment]
I have released a new version with executables targeting macOS 10.12+
Please use latest version of [example1](https://github.com/scapix-com/example1) to test it.
