### ISSUE TITLE
makefile integration?

### ISSUE THREAD

**Issue by fanckush** [scapix-com/scapix#15]
I have a cpp core lib that I would like to use as a backend for different UIs. For now I will start with macOS/swift. The issue is that the cpp lib does not use cmake, is it at all possible to integrate scapix without switching to cmake? my lib is rather simple and I'm currently happy with the makefile setup.

If it is possible, can you give show me an example or point me to the right direction. 
if it matters, I'm planning to use my lib as a statically linked one: `libexample.a`
Thanks a lot

**Comment by Boris-Rasin** [comment]
Using Scapix with makefiles directly may be possible, but it would not be easy. Converting a simple library to use CMake should be trivial and I will be happy to help you with conversion as well as Scapix integration if you grant me access to your repository.

**Comment by fanckush** [comment]
Thanks for the fast reply, i think it's time to switch to Cmake then. I actually lack knowledge in cmake so I probably need to do some readings and learn about it.

I will rarely change the lib while working on the UI, so my workflow is as follows:
* run `make build_lib`
* copy & replace the generated .a file into the separate Xcode project 
* re build the Xcode project and see the changes 

I only expose one class with 4 methods.
``` c++
// class inside mycore namespace
class MyCore {};

// exposed/public methods
void MyCore::MyCore();
bool MyCore::loadFile(const char * path);
void MyCore::process();
void MyCore::save(mycore::format format, u_int &progress);

```

Thanks for the kind offer. it's currently a private repo and I am unable to disclose its contents so I probably have to figure this out on my own. Here is my makefile, maybe you could still give me a tip or two :) 
<details>
  <summary>the messy Makefile snippet</summary>
  
``` Makefile
CXX		  := clang++
CXX_FLAGS := -Wall -Wextra -std=c++14 -g

BIN		:= bin
SRC		:= src
INCLUDE	:= include
LIB		:= -Llib -ltiff

TEST_SRC := $(filter-out src/main.cpp, $(wildcard src/**.cpp) ) $(wildcard tests/**.cpp)
TEST_BIN := test_bin
TEST_EXECUTABLE := test

LIBRARIES	:= /usr/local/lib/libraw.dylib
EXECUTABLE	:= main

SRC_FILES := $(filter-out $(SRC)/main.cpp, $(wildcard $(SRC)/*.cpp))
DEST_LIB := my_lib

all: $(BIN)/$(EXECUTABLE)

run: clean all
	./$(BIN)/$(EXECUTABLE) $(ARGS)

$(BIN)/$(EXECUTABLE): $(SRC)/*.cpp
	$(CXX) $(CXX_FLAGS) -I$(INCLUDE) $(LIB) $^ -o $@ $(LIBRARIES)

$(TEST_BIN)/$(TEST_EXECUTABLE): $(TEST_SRC)
	$(CXX) $(CXX_FLAGS) -I$(INCLUDE) $(LIB) $^ -o $@ $(LIBRARIES)

run_test: clean_test test
	./$(TEST_BIN)/$(TEST_EXECUTABLE)

test: $(TEST_BIN)/$(TEST_EXECUTABLE)

build_objs: $(SRC)/*.cpp
	$(CXX) -c $(CXX_FLAGS) -I$(INCLUDE) $(LIB) $(SRC_FILES) $(LIBRARIES) && mv *.o $(DEST_LIB)

build_lib: build_objs
	ar rcs $(DEST_LIB)/libmycore.a $(DEST_LIB)/*.o

clean_test:
	-rm $(TEST_BIN)/*

clean:
	-rm $(BIN)/*
```
</details>

I haven't integrated scapix yet but I'm sure it will work like magic. so thanks in advance for making this!

**Comment by fanckush** [comment]
Hey @Boris-Rasin I have been trying integrate scapix for a while with no success. When I try to build I get the following error:

``` zsh
[  7%] Linking CXX static library libscapix.a
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
        ar -m [-TLsv] archive file ...
        ar -m [-abiTLsv] position archive file ...
        ar -p [-TLsv] archive [file ...]
        ar -q [-cTLsv] archive file ...
        ar -r [-cuTLsv] archive file ...
        ar -r [-abciuTLsv] position archive file ...
        ar -t [-TLsv] archive [file ...]
        ar -x [-ouTLsv] archive [file ...]
make[2]: *** [_deps/scapix-1.0.19-build/libscapix.a] Error 1
make[1]: *** [_deps/scapix-1.0.19-build/CMakeFiles/scapix.dir/all] Error 2
make: *** [all] Error 2
➜  build git:(master) ✗ 
```
command used to build: `cmake .. && make`. This is the CMakeLists.txt file

``` cmake
cmake_minimum_required(VERSION 3.4)
project(mycore)
include_directories(include)

file(GLOB SOURCES "src/*.cpp")
add_library(test_lib STATIC ${SOURCES})

find_package(TIFF REQUIRED)
include_directories(${TIFF_INCLUDE_DIRS})
target_link_libraries(test_lib PUBLIC ${TIFF_LIBRARIES})

include(FetchContent)
FetchContent_Declare(
  cmodule
  URL "https://github.com/scapix-com/cmodule/archive/v1.0.21.tar.gz"
  URL_HASH SHA256=c27e8467f4c4650f8f98a062fe027ee29ff5442dfa1f47838ca3c5e82e3eb453
)
FetchContent_MakeAvailable(cmodule)

find_package(Scapix REQUIRED)

scapix_bridge_headers(
    test_lib
    "com.example.test_lib"
    "include/MyCore.hpp"
)

```

commenting out the `scapix_bridge_headers` function call stops the error from occurring

**Comment by Boris-Rasin** [comment]
Thank you for reporting this.
I have fixed this problem, it was happening with "SCAPIX_BRIDGE=cpp" CMake parameter (which is the default).
Please use the latest version:

```cmake
FetchContent_Declare(
  cmodule
  URL "https://github.com/scapix-com/cmodule/archive/v1.0.22.tar.gz"
  URL_HASH SHA256=f331d227ae1be52677833baf4fd4728a7c6ee66ec570db6e60d22db0ae43854f
)
```

But eventually, to generate bindings, you need to build for specific language, for example:
 ```bash
cmake -D SCAPIX_BRIDGE=objc ..
```

**Comment by fanckush** [comment]
Thanks @Boris-Rasin for the quick fix. I was successfully able to link it this time however, I get the following error:
``` sh
error: no template named 'auto_ptr' in namespace 'std'
```
`auto_ptr` has been removed in c++17 which is one way to explain the error even though i use this flag: `-std=c++14`
I am not sure what is happening is scapix somehow ignoring or overriding it? when I comment out bridging header function the build succeeds 🤔

**Comment by Boris-Rasin** [comment]
Scapix requires C++17, but you can enable `std::auto_ptr` even in C++17 mode:

```cmake
add_compile_definitions(_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR)
```
