### ISSUE TITLE
vcpkg integration

### ISSUE THREAD

**Issue by luciy-marciy** [scapix-com/scapix#16]
Hello! Firstly thanks for your work! I think that this library should be in vcpkg (it's a C/C++ package manager written by Microsoft).

I'm trying to make a port. And I have some questions. Scapix has ScapixBin as a dependency. ScapixBin lays in another repo. And there are only 3 binary files. Do you have sources of these binaries anywhere in repos? Or I should download these binaries like in cmodule ?

**Comment by Boris-Rasin** [comment]
Thanks for doing this!
I haven't released those sources and anyway the build is complicated (it compiles llvm/clang in the process), so you better include binaries in the package.
Please tell me if there is anything I can help you with.
