### ISSUE TITLE
How does scapix parse C++ headers?

### ISSUE THREAD

**Issue by Time0o** [scapix-com/scapix#20]
I accidentally closed an identical issue earlier, here it is again:

I'm not sure if opening an issue for this is appropriate but I have a question regarding scapix's implementation.

I've started to work on a similar project before I came across this and I'm wondering whether scapix can already do what I was trying to achieve. But after skimming through the website and the source code I still don't quite understand how scapix generates bindings. In particular, at some point it must surely parse the C++ headers for which bindings should be generated.

In my project I use Clang for this and then generate Bindings by working with the generated AST via Clang's C++ interface. However, I don't see scapix doing this. The code base seems to consist almost solely of target language specific stuff and is in general much smaller than I would have expected it to be.

So how exactly does scapix process C++ headers?

**Comment by Boris-Rasin** [comment]
Yes, Scapix does exactly what you describe - to parse C++ headers it uses Clang's generated AST via Clang's C++ interface. This part of Scapix is released in [binary form](https://github.com/scapix-com/scapix-bin) for various platforms, as compiling Clang takes a lot of time and storage. I also didn't release sources for this part of Scapix yet, but I plan to do so at some point.

If you are missing some features in Scapix or have any other suggestions please let me know.

**Comment by Time0o** [comment]
Thanks for the quick reply. I think that answers my question, I will try and see if I apply Scapix to my use case.
