### ISSUE TITLE
[question] How to Install Scapix to CLion Project?

### ISSUE THREAD

**Issue by highjeans** [scapix-com/scapix#21]
@Boris-Rasin  I am developing an IOS app and I wanted to use Scapix in it. For the c++ files I am using CLion. Where should I clone the scapix repo to use it? Here is my project structure: 
<img width="261" alt="Screen Shot 2021-02-16 at 12 28 29 PM" src="https://user-images.githubusercontent.com/77588045/108121813-3abf9880-7058-11eb-9a2b-5f9c10834280.png">

**Comment by highjeans** [comment]
Also does Scapix work with C++20?

**Comment by Boris-Rasin** [comment]
You don't need to clone Scapix repository.
You need to modify your CLion `CMakeLists.txt` project file to use Scapix.

See these examples:
[CMakeLists.txt](https://github.com/scapix-com/scapix_example_objc/blob/master/cpplib/CMakeLists.txt)
[CMakeLists.txt](https://github.com/scapix-com/example1/blob/master/CMakeLists.txt)

You need to add these lines:

```cmake
include(FetchContent)
FetchContent_Declare(
  cmodule
  URL "https://github.com/scapix-com/cmodule/archive/v1.0.27.tar.gz"
  URL_HASH SHA256=02c767f8fededb8b3bc410ceb0565e0d3a58b478f0de9dc3bba92d9d371e65f3
)
FetchContent_MakeAvailable(cmodule)

find_package(Scapix REQUIRED)

scapix_bridge_headers(
    <TARGET> # replace this with your target name
    "com.example.chat"  # replace this with your app domain
    "source/chat/contact.h"   # replace these with your headers path names
    "source/chat/session.h"
)
```

And yes, Scapix works with C++20.

**Comment by highjeans** [comment]
So I add these lines to the CMakeFile.txt in my CLion Project?

**Comment by Boris-Rasin** [comment]
Yes

**Comment by highjeans** [comment]
And where should I create the C++ Project? Inside C++ Classes?

**Comment by highjeans** [comment]
Thanks for helping!
