### ISSUE TITLE
[question] Catching Exceptions?

### ISSUE THREAD

**Issue by highjeans** [scapix-com/scapix#22]
Is there a way to catch an exception thrown by c++ in swift? or in the ui?

**Comment by highjeans** [comment]
Also are custom enums supported?

**Comment by Boris-Rasin** [comment]
No, unfortunately I didn't implement C++ exception handling tunneling for Swift bridge.
I implemented it only for Java and C# briges.
I will look into adding support for Swift too.

Enums are supported, but passed as underlying integer type, no named enums are generated.
I am working on generating named enums now.

**Comment by highjeans** [comment]
Ok Thanks

**Comment by highjeans** [comment]
Could you elaborate on the enums please? What you said doesn't make much sense.

**Comment by Boris-Rasin** [comment]
A C++ function with enum type as parameter (like `enum_test1` function in [session.h](https://github.com/scapix-com/example1/blob/master/source/chat/session.h) example header) is bridged to Swift, but as a function receiving int parameter.

In the future, Scapix will generate corresponding Swift enum type and such function will use the generated Swift enum as parameter.

**Comment by highjeans** [comment]
Ok thanks a lot!

**Comment by TimPushkin** [comment]
@Boris-Rasin Are Swift exceptions still unsupported? If it is so, are there any plans for supporting this?

**Comment by Boris-Rasin** [comment]
Swift exceptions still unsupported.
I have plans to support it, but it will probably take quite some time.
