### ISSUE TITLE
'scapix/bridge/object.h' file not found in Xcode After build in CLion

### ISSUE THREAD

**Issue by highjeans** [scapix-com/scapix#23]
I hit Build in CLion and I went to Xcode to continue making my app and suddenly I see the error message above. I looked at CLion and everything looked fine but it just won't build in Xcode.

**Comment by Boris-Rasin** [comment]
You need to add generated `scapix_XXX.xcconfig` file to your ObjC/Swift XCode project.
This file contains required include paths.

See description in the README file for [scapix_example_objc](https://github.com/scapix-com/scapix_example_objc) example project.

**Comment by highjeans** [comment]
And if there was no scapix_XXX.xconfig generated then?

**Comment by Boris-Rasin** [comment]
The file is created in CMake binary folder.
I don't know where exactly this folder is located when CLion is running CMake, you will have to look for yourself. This is the folder with `CMakeCache.txt` file.

Also, you don't have to use CLion at all. You can setup your project exactly as [scapix_example_objc](https://github.com/scapix-com/scapix_example_objc) project is setup, and do everything from XCode, both Swift and C++.

**Comment by highjeans** [comment]
I setup the library files the same way as it is in the example project you linked, but I am getting this error:

```
CMake Error at build/cmodule-prefix/tmp/cmodule-download.cmake:204 (include):
  include called with invalid argument: Virtual
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.20/Modules/ExternalProject.cmake:3927 (include)
  /Applications/CMake.app/Contents/share/cmake-3.20/Modules/FetchContent.cmake:907:EVAL:2 (_ep_do_preconfigure_steps_now)
  /Applications/CMake.app/Contents/share/cmake-3.20/Modules/FetchContent.cmake:907 (cmake_language)
  /Applications/CMake.app/Contents/share/cmake-3.20/Modules/FetchContent.cmake:1044:EVAL:2 (__FetchContent_directPopulate)
  /Applications/CMake.app/Contents/share/cmake-3.20/Modules/FetchContent.cmake:1044 (cmake_language)
  /Applications/CMake.app/Contents/share/cmake-3.20/Modules/FetchContent.cmake:1087 (FetchContent_Populate)
  CMakeLists.txt:11 (FetchContent_MakeAvailable)


CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "FindScapix.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Scapix", but
  CMake did not find one.

  Could not find a package configuration file provided by "Scapix" with any
  of the following names:

    ScapixConfig.cmake
    scapix-config.cmake

  Add the installation prefix of "Scapix" to CMAKE_PREFIX_PATH or set
  "Scapix_DIR" to a directory containing one of the above files.  If "Scapix"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```
I have also attached the log file. I don't really know why this is happening.
[CMakeOutput.log](https://github.com/scapix-com/scapix/files/6011864/CMakeOutput.log)

**Comment by highjeans** [comment]
I used the same project structure as the example linked in your last comment.

**Comment by Boris-Rasin** [comment]
Can you post content of your `CMakeLists.txt` file, please?

**Comment by highjeans** [comment]
```
cmake_minimum_required(VERSION 3.14)

project(cpplib)

include(FetchContent)
FetchContent_Declare(
  cmodule
  URL "https://github.com/scapix-com/cmodule/archive/v1.0.27.tar.gz"
  URL_HASH SHA256=02c767f8fededb8b3bc410ceb0565e0d3a58b478f0de9dc3bba92d9d371e65f3
)
FetchContent_MakeAvailable(cmodule)

find_package(Scapix REQUIRED)

file(GLOB_RECURSE bridge_headers CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/source/*.h)
scapix_add_target(cpplib "com.example.cpplib" "${bridge_headers}")

file(GLOB_RECURSE sources CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/source/*)
source_group(TREE ${CMAKE_CURRENT_LIST_DIR} FILES ${sources})
target_sources(cpplib PRIVATE ${sources})

target_include_directories(cpplib PUBLIC ${CMAKE_CURRENT_LIST_DIR})
```

**Comment by highjeans** [comment]
same as the CMakeLists.txt file in the example project

**Comment by Boris-Rasin** [comment]
And you are running `cmake -B build -G "Xcode" -DSCAPIX_BRIDGE=objc` and getting the `find_package` error?

I see you are using pre-release version of CMake (version 3.20 rc1). I haven't tested with this version. Could you try with latest released version of CMake (version 3.19.5)?

**Comment by highjeans** [comment]
Ok I will try that. but quick question, where do I find the latest version?

**Comment by highjeans** [comment]
THANKS SO MUCH IT WORKED!!!!!!

**Comment by highjeans** [comment]
Last question for the last step where we add to the configurations, where would you add it in Xcode 12.4? Attached is a photo of what's already there. NOTE: everything that was drawn over had the app name in it.
<img width="587" alt="Screen Shot 2021-02-19 at 10 26 05 AM" src="https://user-images.githubusercontent.com/77588045/108545837-25877b80-729d-11eb-8a11-41266b6ddd00.png">

**Comment by Boris-Rasin** [comment]
Where it says `None` it should be `scapix_XXX`, where `XXX` is the name of your C++ project.

**Comment by highjeans** [comment]
Thanks a lot!

**Comment by highjeans** [comment]
Should the xcconfig file go inside the same folder as AppDelegate or a different folder?

**Comment by highjeans** [comment]
Also the app is written in swift, not Objective-C , and I used the same .sh file that is in the objc example, so Is that bad? Because I am trying to make a new object from the c++ class and is says "Not found in scope"

**Comment by Boris-Rasin** [comment]
xcconfig file should be at the top project level.

For Swift, you also need to configure Apple XCode Swift bridge headers for this project: [importing_objective-c_into_swift](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift)

**Comment by highjeans** [comment]
Thanks so much!
