### ISSUE TITLE
ld: library not found for -l<your cpp lib>

### ISSUE THREAD

**Issue by FRANZEE** [scapix-com/scapix#24]
Hello, traing to use Scapix in my project for IOS.
Tested scapix_example_objc it works fine.
Tryed to integrate to my project and error  below are occured.

`
Ld /Users/user/Library/Developer/Xcode/DerivedData/scapix_example-gatyqgsxryvuoydydfdqoiulcxgq/Build/Products/Debug-iphonesimulator/iosapp.app/iosapp normal (in target 'iosapp' from project 'iosapp')
    cd /Users/user/mydata/code/ios/test/objc/example4/scapix_example_objc/iosapp
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios14.5-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -L/Users/user/Library/Developer/Xcode/DerivedData/scapix_example-gatyqgsxryvuoydydfdqoiulcxgq/Build/Products/Debug-iphonesimulator -F/Users/user/Library/Developer/Xcode/DerivedData/scapix_example-gatyqgsxryvuoydydfdqoiulcxgq/Build/Products/Debug-iphonesimulator -filelist /Users/user/Library/Developer/Xcode/DerivedData/scapix_example-gatyqgsxryvuoydydfdqoiulcxgq/Build/Intermediates.noindex/iosapp.build/Debug-iphonesimulator/iosapp.build/Objects-normal/x86_64/iosapp.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/scapix_example-gatyqgsxryvuoydydfdqoiulcxgq/Build/Intermediates.noindex/iosapp.build/Debug-iphonesimulator/iosapp.build/Objects-normal/x86_64/iosapp_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -lswiftapi -lscapix -lc++ -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/scapix_example-gatyqgsxryvuoydydfdqoiulcxgq/Build/Intermediates.noindex/iosapp.build/Debug-iphonesimulator/iosapp.build/iosapp.app-Simulated.xcent -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/scapix_example-gatyqgsxryvuoydydfdqoiulcxgq/Build/Intermediates.noindex/iosapp.build/Debug-iphonesimulator/iosapp.build/Objects-normal/x86_64/iosapp_dependency_info.dat -o /Users/user/Library/Developer/Xcode/DerivedData/scapix_example-gatyqgsxryvuoydydfdqoiulcxgq/Build/Products/Debug-iphonesimulator/iosapp.app/iosapp

ld: library not found for -lswiftapi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

I am tottaly new for c++, can you please provide any suggestions?

**Comment by Boris-Rasin** [comment]
What are the names of your Swift and C++ targets?
Is one of your targets named "swiftapi"?

If you can place this project on github and grant me access, I will fix it for you.
