### ISSUE TITLE
Avoid generation for all specified languages

### ISSUE THREAD

**Issue by anastasiia-kornilova** [scapix-com/scapix#25]
Good day! Many thanks for this great tool! Could you, please, give me a tip -- is there a way to generate files only for the target platform? For example, in our case, we build a bridge from C++ library to Java-code in Android app and wonder is there a flag/option not to generate bindigs for other languages (Swift, js, python, etc)?

**Comment by Boris-Rasin** [comment]
Hello!

Such an option would not save any time - the majority of time is spent parsing C++ header (only once), the subsequent generation of bindings (for all languages) takes very little time in comparison. That's why I decided against such an option. Is there any other reason you want this option?

**Comment by anastasiia-kornilova** [comment]
Actually, the main reason is to have less overhead and files that are not-related explicitly to the project. But it is not very crucial for our project, so my question was more about interest.

Many thanks one more time for the tool!

**Comment by Boris-Rasin** [comment]
Thanks!

If you have any other questions or requests please don't hesitate to ask.
