### ISSUE TITLE
Learn more about SCAPIX_PLATFORM

### ISSUE THREAD

**Issue by pmokeev** [scapix-com/scapix#26]
Good day!
Could you tell me in more detail what the CMake SCAPIX_PLATFORM parameter means? I found only one use of it in the example on GitHub. I would like to learn more :)
Thank you for such a wonderful tool!

**Comment by Boris-Rasin** [comment]
Hello!

Some documentation is here: https://www.scapix.com/language_bridge/cmake_integration

This is an optional parameter, and strictly speaking not really a part of Scapix bindings generator.

I added this parameter as a "useful pattern" for cross-platform C++ code which also contains parts of platform-dependent C++ code. For example, if your cross-platform project also has some platform dependent code for Windows and macOS, you can place this code in "platform/windows" and "platform/macos" folders and specify `SCAPIX_PLATFORM` as "windows" or "macos" respectively. This will compile code from appropriate platform folder and ignore code from other platform folders.

If you don't have any platform specific C++ code (or you deal with such code using #ifdef) - you don't need this option.

**Comment by pmokeev** [comment]
Excellent. Thank you for such a detailed answer :)
