### ISSUE TITLE
Adding another library dependency fails

### ISSUE THREAD

**Issue by nishiths23** [scapix-com/scapix#29]
When I try to add another dependency using the provided example it fails with the following error

```
Cannot specify link libraries for target "PRIVATE" which is not built by
[cmake]   this project.
```

INFO:
I am trying to add the dependency using the following code

```
find_package(ZLIB REQUIRED)
target_link_libraries(${target} PRIVATE ZLIB::ZLIB)
```

From this link - https://www.scapix.com/language_bridge/cmake_integration/

**Comment by Boris-Rasin** [comment]
Looks like your ${target} variable expended to empty string, so CMake thinks you are trying to add dependency to target named "PRIVATE" which obviously does not exist.

**Comment by nishiths23** [comment]
Oh I'm new to CMake can you please suggest how to resolve this issue because if I use my library name instead of ${target} I get the following error:



The keyword signature for target_link_libraries has already been used with
  the target "cpplib".  All uses of target_link_libraries with a target must
 be either all-keyword or all-plain.
 
   The uses of the keyword signature are here:
 
    * {path to c module}/.cmodule/scapix/1.0.25/CMakeLists.txt:175 (target_link_libraries)

**Comment by Boris-Rasin** [comment]
Adding keyword PUBLIC or PRIVATE should fix this:

target_link_libraries(cpplib PRIVATE NFHTTP)

**Comment by nishiths23** [comment]
It worked. @Boris-Rasin Thank you so much.
