### ISSUE TITLE
C++20 when?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [scapix-com/scapix#30]

**Comment by Boris-Rasin** [comment]
I already have this done, will release in the next few days.
C++20 will be supported, but not required.

**Comment by Boris-Rasin** [comment]
https://github.com/scapix-com/scapix/commit/5e9dbcc684c65111a15274d9b60b4056f401d6b4

**Comment by Boris-Rasin** [comment]
Scapix with support for C++17 / C++20 / C++23 is released (cmodule v1.0.32):
https://github.com/scapix-com/cmodule/releases

Set your target to C++20 mode:
```cmake
target_compile_features(mylib PUBLIC cxx_std_20)
```
and Scapix will use C++20 mode when parsing headers.
