### ISSUE TITLE
std::function parameter in std::function

### ISSUE THREAD

**Issue by nadrolinux** [scapix-com/scapix#33]
Hello,
At first, congrats for this very interesting project. I try to implement it into project and found a first problem. A following code doesn't compile:
```
class TestCase : public scapix::bridge::object<TestCase>
{
public:
    void problem(std::function<void(std::function<void()>)> value){};
};
```
I see a following error (I try to generate JNI bridges for Android):
```
error: no member named 'jni' in 'scapix::link::java::convert<scapix::link::java::ref<scapix::link::java::function<scapix::meta::string<'p', 'l', '/', 'a', 'b', 'c', '/', 't', 'e', 's', 't', '/', 'T', 'e', 's', 't', 'C', 'a', 's', 'e', '$', 'F', 'u', 'n', 'c', 't', 'i', 'o', 'n', '1'>, void ()>, scapix::link::java::detail::api::scope::generic>, std::function<void ()>>'
```

Do you have any plans about implement support for stuff like this?
Best regards,

**Comment by Boris-Rasin** [comment]
Thank you, it's great to hear you like the project.

I knew this functionality was missing (for Java bridge, it is implemented for Objective C/Swift). Never got around to implementing it, since no one asked. I will implement it now, should be ready in a few days.

**Comment by nadrolinux** [comment]
Hello,
How looks a situation with this issue?
Patryk

**Comment by Boris-Rasin** [comment]
48c34a9cec69f2ef418d94e56bcd08602e5e78c6

**Comment by nadrolinux** [comment]
It seems to work. Thanks for a fix!
