### ISSUE TITLE
file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by womaas** [scapix-com/scapix#35]
Hi. How to fix this? I can't replace all <> with "" manually in a thousand files.

**Comment by Boris-Rasin** [comment]
Where do you get this error? Please provide more information what did you do when you got this error, full error message, etc.

**Comment by womaas** [comment]
When I try to compile C++ code to WebAssembly. The error looks like:
`'filename.hxx' file not found with <angled> include, use "quotes" instead`.

C++ file has:
`#include <filename.hxx>`

**Comment by Boris-Rasin** [comment]
This looks unrelated to Scapix.

You probably need to add CMake command `target_include_directories(<target> PUBLIC <dir>)` to the relevant directory with header files.

I can help you fix this, if you fork example1 project and commit your changes to github.

**Comment by womaas** [comment]
Looks like the mistake was that I didn't fix
`.h`
to the
`.hxx`

But now there is another error:
```
fatal error: 'Filename.hxx' file not found
#include <filename.hxx>
```

All files, including `.hxx`, are located in the `src `folder, including subfolders. A file from one subfolder can link to a file from another (as in the example above). Here is the config: 
`cmake_minimum_required(VERSION 3.14)

project(chatlib)

include(FetchContent)
FetchContent_Declare(
  cmodule
  URL "https://github.com/scapix-com/cmodule/archive/refs/tags/v1.0.32.tar.gz"
  URL_HASH SHA256=e6937c95d73188a5add846b27cd00160fe4f6ea31af33be417d2ab7ac19bd8d2
)
FetchContent_MakeAvailable(cmodule)

file(GLOB_RECURSE bridge_headers CONFIGURE_DEPENDS "src/*.h")
file(GLOB_RECURSE sources CONFIGURE_DEPENDS "src/*")
source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}/src" PREFIX "src" FILES ${sources})

find_package(Scapix REQUIRED)

scapix_add_target(chatlib "com.example.chat" ${bridge_headers})
target_sources(chatlib PRIVATE ${sources})
target_include_directories(chatlib PUBLIC src)

if(EXISTS "ui/${SCAPIX_BRIDGE}/CMakeLists.txt")
  add_subdirectory("ui/${SCAPIX_BRIDGE}")
endif()`

**Comment by Boris-Rasin** [comment]
Find out where file "filename.hxx" is located and add it's directory to the include directories list.
For example, if file "filename.hxx" is in directory "src/include":

```cmake
target_include_directories(chatlib PUBLIC src src/include)
```

**Comment by womaas** [comment]
I have only described one case. There are hundreds of such files. Is there a way to tell it to search for header files recursively? Like `GLOB_RECURSE` above?

**Comment by Boris-Rasin** [comment]
Someone wrote CMake macro for this:
https://stackoverflow.com/questions/17653738/recursive-cmake-search-for-header-and-source-files

```cmake
MACRO(HEADER_DIRECTORIES return_list)
    FILE(GLOB_RECURSE new_list *.h)
    SET(dir_list "")
    FOREACH(file_path ${new_list})
        GET_FILENAME_COMPONENT(dir_path ${file_path} PATH)
        SET(dir_list ${dir_list} ${dir_path})
    ENDFOREACH()
    LIST(REMOVE_DUPLICATES dir_list)
    SET(${return_list} ${dir_list})
ENDMACRO()
```
Usage:

```cmake
HEADER_DIRECTORIES(header_dir_list)

list(LENGTH header_dir_list header_dir_list_count)
message(STATUS "[INFO] Found ${header_dir_list_count} header directories.")

target_include_directories(
    my_program
    PUBLIC
    ${header_dir_list} # Recursive
)
```

This may save you time in your specific case, but generally the right way would be to always include headers relative to some root directory (in your case "src"):

```c++
#include <mydir/subdir/header.h>
```

So this single command would be enough for all headers:

```cmake
target_include_directories(chatlib PUBLIC src src/include)
```

**Comment by womaas** [comment]
Thanks. That helped.
New errors, but already at the linking stage:
```
wasm-ld: error: duplicate symbol: NAME HERE IN UPPERCASE
>>> defined in CMakeFiles/chatlib.dir/src/name_of_the_file.cxx.o
>>> defined in CMakeFiles/chatlib.dir/src/another_name_of_the_file.cxx.o
```
Is there any way to ignore this error? For example, skip files that define a symbol if it is already defined.

**Comment by Boris-Rasin** [comment]
This is a bug in C++ code you are trying to compile.
I will need to see the code to help you.

Either this symbol is defined in both cxx files, or (problematically) defined in a header file they both include.

**Comment by womaas** [comment]
For now, I just deleted the conflicting files, because they are not important yet. Another error (nothing else to remove and I can't fix source files): 
```
cmd.exe /C "cd . && C:\emsdk\upstream\emscripten\em++.bat  --bind @CMakeFiles\chatlib.rsp -o chatlib.js  && cd ."
error: undefined symbol: __cxa_is_pointer_type (referenced by $CatchInfo__deps: ['$ExceptionInfo','__cxa_is_pointer_type'], referenced by __cxa_find_matching_catch_3__deps: ['$exceptionLast','$ExceptionInfo','$CatchInfo','__resumeException','__cxa_can_catch'], referenced by top-level compiled C/C++ code)
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
```

**Comment by Boris-Rasin** [comment]
This seems to be related to C++ exception handling. In my test code with C++ exceptions, this does not happen. Perhaps your code is using some specific types in C++ `throw` or `catch` statements, which leads to this issue.

**Comment by womaas** [comment]
Ok, I'm trying to recompile with a different file location:
```
error: expected namespace name
using namespace System;
```
file.h:
```
...
using namespace System;
...
```

**Comment by womaas** [comment]
After several attempts, I eventually got a wasm file, but a very small one. With the total size of all .o files being about 200 Mb, the .wasm file is only 1 Mb.

**Comment by Boris-Rasin** [comment]
For Scapix to generate bindings, you need to derive your C++ classes from `scapix::bridge::object` class:
https://www.scapix.com/language_bridge/introduction/

**Comment by womaas** [comment]
The main page says:
`Automatic, on the fly bindings from C++ to Java, Objective-C, Swift, Python, JavaScript (WebAssembly) and C#. Bridge code automatically generated directly from C++ header files, no need to manually maintain IDL definitions or bindings.`
So it's not possible to just take a big project with a thousand files and generate bindings automatically?

**Comment by Boris-Rasin** [comment]
Scapix does generate bindings automatically, by parsing C++ headers, unlike various other tools which require you to manually describe each function with each parameter, using some language separate from C++.

Scapix however, currently does require you to (slightly) modify C++ code to do it.

I am working on an unintrusive version of Scapix, which will allow one to generate bindings for unmodified C++ code, but this is still work in progress.

**Comment by womaas** [comment]
But modifying thousands of files without knowing C++ can be a daunting task. The new Scapix will be the solution. Will this new functionality be reflected on the main page of the project as soon as the new version is ready?

**Comment by Boris-Rasin** [comment]
It will definitely be in the [changelog](https://www.scapix.com/language_bridge/changelog/) and probably on the main page too.

**Comment by womaas** [comment]
Thanks.
