### ISSUE TITLE
JNI FindClass return null on Android main thread

### ISSUE THREAD

**Issue by nadrolinux** [scapix-com/scapix#37]
Hello,
I found a serious problem with Scapix for Android. Problem is related to a following method:
```
// source/scapix/link/java/class.h
static local_ref<class_> find_class(const char* name)
{
	jclass cls = detail::env()->FindClass(name);
	detail::check_exception(cls);
	return local_ref<class_>(cls);
}
```
It looks like a standard system vs. application class loader problem. Thats why in manually written bridges I cached jclass at JNI_OnLoad step, however I can't do that similar trick with Scapix.

To produce this issue on Xiaomi phone with Android 12 I just needed to create simple lambda like a:
```
[this]() -> void
{
	std::shared_ptr<A> a = std::make_shared<A>();
	mCallbackForA(a); // FindClass return null for a, null for NativeException and next abort
}
```
and enqueue it from a main thread to Android main thread via standard Android looper (solution required for async tasks with final steps at main thread, just I didn't even need to spawn a secondary std::thread for this test). I even compared std:: thread ::id, just to ensure it's not a bug in my app. After that steps FindClass returned null for all my classes and Scapix classes like a NativeException thats why finally I've got '__cxa_guard_acquire detected recursive initialization' error. Maybe you know some quick, temporary workaround for this issue in Scapix? This issue block a release of important update to our app.
Best regards,
Patryk

**Comment by Boris-Rasin** [comment]
I am looking into this, will get back to you soon.

**Comment by nadrolinux** [comment]
Great, thanks.

**Comment by Boris-Rasin** [comment]
I am still working on fully automated solution (using cached ClassLoader object instead of JNI FindClass API).

In the mean time, you can use this workaround. Somewhere in the thread where FindClass works, add calls to class_object() function for each of the classes you will need in the Android main thread:

```c++
	scapix::link::java::object<SCAPIX_META_STRING("com/scapix/Bridge")>::class_object();
	scapix::link::java::object<SCAPIX_META_STRING("com/scapix/NativeException")>::class_object();
```

This will lookup and cache class object for each listed class.

**Comment by Boris-Rasin** [comment]
I committed code with `SCAPIX_CACHE_CLASS_LOADER` feature: https://github.com/scapix-com/scapix/commit/c3947725d82c9a09fa33c97c466fc1cd472245f6

This feature is optional, to enable add to your CMake file:

```cmake
target_compile_definitions(scapix PUBLIC SCAPIX_CACHE_CLASS_LOADER)
```

Please test if it works for your case. Don't forget to remove `class_object()` workaround calls for the test.

Thanks.

**Comment by nadrolinux** [comment]
I added this line after find_package(Scapix REQUIRED) and before scapix_bridge_headers, but I see a following compilation error:
`source/scapix/link/java/init.h:41:138: error: use of undeclared identifier 'string'; did you mean 'std::string'?`

**Comment by Boris-Rasin** [comment]
Sorry about that. I think I fixed it (https://github.com/scapix-com/scapix/commit/0d7aa8fa51a90755e97f6ab54f5b9b7ba6583f4a), please try again.

**Comment by nadrolinux** [comment]
No problem. I tested the latest code and it works great. I didn't notice any issues.

**Comment by Boris-Rasin** [comment]
Great!

I will release a new (cmodule) version soon.
