### ISSUE TITLE
Null pointer dereference (Android + JNI)

### ISSUE THREAD

**Issue by nadrolinux** [scapix-com/scapix#39]
Hello,
At first, it's not a high priority issue in my opinion, but I found that Scapix may crash at:
```
// source/scapix/link/java/detail/api/ref.h
static jobject new_ref(jobject h) noexcept { return detail::env()->NewGlobalRef(h); }
```
Probably 'scope::local' and 'scope::weak' variants are also vulnerable to this issue.

When crash occurred I saw that 'jobject h' was nullptr, so 'NewLocalRef' caused abort with 'null pointer dereference' info. This issue may appear eg. when you store lambda with captured std::function to std::function (Scapix function stored here)  and next you copy this std::function on another thread. I think that it may be relatated to detached JNI environment on another thread. I don't know if Scapix do some check like this one:
`if (pVM->GetEnv((void**)&mEnvironment, JNI_VERSION_1_6) == JNI_EDETACHED && pVM->AttachCurrentThread(&mEnvironment, nullptr) == JNI_OK)`
but if not it may be source of problem. However this issue may be relative easy solved by just store std::shared_ptr with std::function, so copy operate just on std::pointer instead of std::function, thats why I think that priority of this issue isn't high.

Best regards,
Patryk

**Comment by Boris-Rasin** [comment]
As a workaround, you can call once in each thread created from C++:

```c++
scapix::link::java::attach_current_thread();
```

For convenience, I can also add generic version of this function (which will do nothing with other bridge languages):

```c++
scapix::init_thread();
```

I can also add optional automatic thread attachment:

```cmake
target_compile_definitions(scapix PUBLIC SCAPIX_JNI_AUTO_ATTACH_THREAD)
```

I want to make it optional because it would add slight runtime overhead on each JNI call.

What do you think?

**Comment by nadrolinux** [comment]
Hi,
I think that 3rd option with optional auto attachments is the best, because of automatic nature, but I agree that marked it as optional is better choice, because in this way we can still rely on options 1 and/or 2 if auto performance will be a problem. Please just remember that for option no. 2 you should also add 'scapix::exit_thread' or similar with internal 'scapix::link::java::detach_current_thread()' call.
Thanks for a quick response and good solutions as always.
Patryk

**Comment by Boris-Rasin** [comment]
Commit: https://github.com/scapix-com/scapix/commit/0256e3fc9cb4e997474c96646de58dc7f7e9a77b
Documentation: https://www.scapix.com/java_link/threads/

**Comment by Boris-Rasin** [comment]
Released in cmodule v1.0.35:
https://github.com/scapix-com/cmodule/releases

**Comment by nadrolinux** [comment]
Great, thanks a lot.

**Comment by nadrolinux** [comment]
I tested this feature, but even with:
`target_compile_definitions(scapix PUBLIC SCAPIX_JAVA_AUTO_ATTACH_THREAD)`
I see a crash due to:
```
// source/scapix/link/java/details/api/type.h
template <typename ...Args> static void call_method(jobject obj, jmethodID id, Args... args) noexcept { env()->CallVoidMethod(obj, id, args...); }
// jni.h
functions->CallVoidMethodV(this, obj, methodID, args); // crash here, obj is null
```
I try to provide to you some more details, eg. logs, but it's not that easy. First captured std::function works properly, but second is null after some time and I don't know why.
