### ISSUE TITLE
Is C# supported on Linux and/or macOS?

### ISSUE THREAD

**Issue by emmenlau** [scapix-com/scapix#44]
Awesome library, great work! Are the C# bindings supported on Linux too? In the [example](https://github.com/scapix-com/example1), it mentions specifically how to generate the bindings on Windows, but not other platforms.

**Comment by Boris-Rasin** [comment]
Thanks!

Yes, C# bindings are supported on all platforms, see build scripts in [example1](https://github.com/scapix-com/example1):

[default_cs.sh](https://github.com/scapix-com/example1/blob/master/default_cs.sh)
[xcode_cs.sh](https://github.com/scapix-com/example1/blob/master/xcode_cs.sh)

**Comment by emmenlau** [comment]
Thanks, thats great news! Two thumbs up!
