### ISSUE TITLE
Enum class is not propagated to the Python bindings.

### ISSUE THREAD

**Issue by zvasicek56** [scapix-com/scapix#49]
Enums are correctly recognised and treated as ints in Java bindings. In Python, however, enums do not work because of the missing declaration.

The C++ code
```cpp
enum class MyEnum { One = 1, Two };

MyEnum test_return_enum() { return MyEnum::One;}

```
Causes exception:
```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    c.test_return_enum()
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: tests.main) -> tests::MyEnum
```

To FIX this issue, the scapix generator should generate the following code

```cpp
pybind11::enum_<MyEnum>(m, "MyEnum", pybind11::arithmetic())
        .value("One", MyEnum::One)
        .value("Two", MyEnum::Two)
        .export_values();
```

**Comment by Boris-Rasin** [comment]
Thanks for report.

I am implementing this now.

Do you think I should always specify `pybind11::arithmetic()` for every enum?

**Comment by zvasicek56** [comment]
Thanks for your quick reply and your efforts, Boris.

According to the [documentation](https://pybind11.readthedocs.io/en/latest/classes.html?highlight=enum#enumerations-and-internal-types), `pybind11::arithmetic` creates an enumeration that supports rudimentary arithmetic and bit-level operations like comparisons, and, or, xor, negation, etc. This means, for example, that the options can be used as bit flags.

I would suggest specifying this behaviour only for enums derived from standard integer types, i.e. those that have the underlying type. 

```cpp
enum class MyEnum : std::uint32_t { One = 1, Two };
```

C++ doesn't directly support flags on enumeration type, but you can overload the `|` operator and use the underlying type for the math as discussed [here](https://stackoverflow.com/questions/32578638/how-to-use-c11-enum-class-for-flags). So it makes sense to allow this in Python as well.

**Comment by Boris-Rasin** [comment]
I have released new version with the fix.

Please update cmodule to the latest [version](https://github.com/scapix-com/cmodule/releases).
Changelog is [here](https://www.scapix.com/language_bridge/changelog).
