### ISSUE TITLE
Map containing vectors in Java

### ISSUE THREAD

**Issue by zvasicek56** [scapix-com/scapix#52]
The following C++ code 

```cpp

class tester : public scapix::bridge::object<tester>
{
public:
    void test_map(std::vector<std::string> list_strings,
                           std::vector<std::uint8_t> list_bytes,
                           std::unordered_map<std::string, std::string> map_string,
                           std::unordered_map<std::uint16_t, std::string> map_string2,
                           std::unordered_map<std::uint16_t, std::vector<std::uint8_t>> map_bytes) {};
}
```

works when used in Python binding. The Java binding, however, can't be compiled. The compilation fails with a type error caused by the hash map `map_bytes`. It doesn't matter whether ``std::map`` or ``std:hash_map`` is used.

Not sure if this is related to the previous problem, but the code generated for a parameter of `std::vector<std::vector<std::uint8_t>>`  type also causes an error.

**Comment by Boris-Rasin** [comment]
Thank you for the report.

I have released new version with the fix.

Please update cmodule to the latest [version](https://github.com/scapix-com/cmodule/releases).
Changelog is [here](https://www.scapix.com/language_bridge/changelog).
