### ISSUE TITLE
Null parameter for callback from Java to C++

### ISSUE THREAD

**Issue by AzanovAA** [scapix-com/scapix#54]
Let's say we have a function in C++:
```
typedef std::function<void(std::uint64_t requestId)> FinishedCallback;
std::uint64_t executeRequest(FinishedCallback finishedCallback);
```
When I make a call from Java/Kotlin with a null parameter of the finishedCallback, in C++ this parameter is not null.
This code doesn't work correctly:
```
std::uint64_t executeRequest(FinishedCallback finishedCallback)
{
   if (finishedCallback == nullptr) {
     ...
   }
}
```

**Comment by Boris-Rasin** [comment]
Thank you for reporting this issue. This should be easy to fix. I will look into it.

**Comment by AzanovAA** [comment]
Thanks!

**Comment by Boris-Rasin** [comment]
New version v1.0.43 with this fix has been released: [cmodule releases](https://github.com/scapix-com/cmodule/releases)
