### ISSUE TITLE
Error: Failed to checkout tag

### ISSUE THREAD

**Issue by calebbergman** [scapix-com/scapix#7]
### OS: Windows 10 1903

I have [a very simple project](https://github.com/calebbergman/scapix-example) set up to play with scapix. I'm running into an issue when `cmake` runs the `scapix.cmake` file.

```
Checking Build System
Performing download step (git clone) for 'scapix-bin-populate'
Cloning into 'bin'...
fatal: not a git repository (or any of the parent directories): .git
CMake Error at Temp/apps/scapix-example/build/_deps/scapix-bin-subbuild/scapix-bin-populate-prefix/tmp/scapix-bin-populate-gitclone.cmake:40 (message):
  Failed to checkout tag: '7'
```

I'm very new to cmake and scapix, so there very well could be something in my config/source that's causing issue. I confirmed the project builds and runs prior to introducing `scapix` into the equation.

**Comment by Boris-Rasin** [comment]
I have added missing parameters to your [CMakeLists.txt](https://github.com/scapix-com/scapix/files/4048794/CMakeLists.txt)

When running, you should also specify target bridge, for example: `cmake -DSCAPIX_BRIDGE=java -B ./build .`

I also plan to simplify Scapix CMake interface so all these additional config options will not be required, and something like your original CMake will also work.

**Comment by calebbergman** [comment]
Thank you @Boris-Rasin, that helped; I was able to run `cmake` successfully with those changes.

I had seen those additions - like all of the `hunter` items at the top - in the examples of this git repo but didn't think they were a requirement; I had thought `hunter` was only required for adding *additional* 3rd-party dependencies.

Reviewing the docs again I also see that the "SCAPIX_BRIDGE parameter is **required**" when running `cmake` 😅

Looking forward to the simplified CMake interface 😊
