### ISSUE TITLE
Generated library (.so) name incorrect

### ISSUE THREAD

**Issue by calebbergman** [scapix-com/scapix#8]
From my (limited) understanding, a library is named from one's CMakeLists.txt file when calling `add_library`. For instance:

```
add_library {
mylib
SHARED
./native_libs/mylib/mylib.cpp
./native_libs/mylib/mylib.hpp
}
```

The corresponding library name would be "mylib."

I have a similar setup in an [example (Flutter) application](https://github.com/calebbergman/flutter_scapix_example) I've been tinkering with. However, after running `cmake`, `generated/bridge/java/com/example/flutter_example/Person.java` was attempting to load library "flutter_examplelib" instead of "person" (please see [this commit](https://github.com/calebbergman/flutter_scapix_example/commit/3594e3c4079d2627e0a06b0ec5a07c78cbc682e3)).

I'm curious what caused it to generate the wrong library name. Is my configuration incorrect somewhere? 🤔

Thank you very much for your time.

**Comment by Boris-Rasin** [comment]
Project name is taken from second parameter (domain) to scapix_bridge_headers() CMake function. In your case, to get project name "person", you need to call it like this:

```
scapix_bridge_headers(
  person
  "com.example.person"
  "${CMAKE_CURRENT_SOURCE_DIR}/native_libs/person/person.hpp"
)
```

**Comment by calebbergman** [comment]
Ok, thank you. I've been having limited success getting all of this work so I've been trying to follow the [example1](https://github.com/scapix-com/example1) project closely.

I noticed there that in the [CMakeList.txt](https://github.com/scapix-com/example1/blob/master/project/CMakeLists.txt) file the `chatlib` library was namespaced the same as the Android app, namely "com.scapix.chat."

```
scapix_bridge_headers(
    chatlib
    "com.scapix.chat"
    ...
)
```

Then in [MainActivity.java](https://github.com/scapix-com/example1/blob/master/ui/android/app/src/main/java/com/scapix/chat/MainActivity.java), `System.loadLibrary` is loading `chatlib` - the name of the library designated in `CMakeLists.txt`, not the domain parameter `chat`.

That led me down the path that maybe I needed to have my library namespaced the same as the Android application (`com.example.flutter_example`) - but I suppose that's not the case 😉  Thank you for the clarification.
